name: Upload and Generate Signed URL

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  upload-and-sign:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Sync files to S3
#    - name: Upload report to S3
#      uses: jakejarvis/s3-sync-action@master
#      env:
#        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      with:
#        source_dir: allure-report
#        dest_dir: ${{ env.ENVIRONMENT }}/${{ env.DATE }}

    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::440744228769:role/github-assumerole-test
        aws-region: us-east-1


#    # Step 3: Generate Signed URL
#    - name: Generate signed URL
#      uses: aws-actions/cli-configure@v2
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1 # Change this to your S3 bucket's region

    - name: Generate signed URL for S3 object
      run: |
        signed_url=$(aws s3 presign s3://testingwq1234/123/Untitled.rtf --expires-in 604800)
        echo "Signed URL: $signed_url"
        echo "signed_url=$signed_url" >> $GITHUB_ENV
        echo "GITGUB: $GITHUB_ENV"
